### ISSUE TITLE
Plug Testnet nouns NFT contract into member portal token gate

### ISSUE THREAD

**Issue by willyogo** [ATXDAO/nouns-monorepo#21]
AC:
1. If a user holds an atxnouns nft on goerli, they should be able to access the token-gated member portal

Note: creating a separate ticket to remove testnet NFT access from the token gate prior to going live

**Comment by JacobZeroProxy** [comment]
The app now properly reads from the NFT smart contract on Goerli from: 0x373086C336B182b9D9e3874344E46FF0a9630D4E .

this is ready to be closed!
