### ISSUE TITLE
Require members to sign in to Member Portal with Ethereum

### ISSUE THREAD

**Issue by willyogo** [ATXDAO/nouns-monorepo#25]
Currently the token gate on the member portal doesn't use sign in with ethereum. In theory, a user could use a wallet like frame that lets you inject any address and connect to the member portal without actually being a member.

As platform admins, we want to implement Sign in with Ethereum to ensure that only members can access

AC:

In order to access the members portal, users need to sign a message with an account holding an ATXDAO nft

**Comment by willyogo** [comment]
Less of a priority for now; can revisit once we have content that needs to be token gated (hopefully soon!)

**Comment by JacobHomanics** [comment]
https://docs.family.co/connectkit/usesiwe-hook#usesiwe-hook-example

**Comment by willyogo** [comment]
Not possible without a backend. Also we realized that if anyone really wanted to get through the token gate they could because it's all in the open source code
