### ISSUE TITLE
Cannot connect Coinbase Wallet

### ISSUE THREAD

**Issue by kaynelynn** [ATXDAO/nouns-monorepo#26]
I have successfully gotten into the member's portal in the past. This time, when I first arrived clicking Coinbase Wallet showed me the QR code, and I scanned and signed on my mobile device. The page did not refresh, and now I cannot proceed. 

Clicking coinbase wallet or clear wallet connect data neither do anything for me. I have attached a screen recording of the logs that this is generating in my browser. 

https://github.com/ATXDAO/nouns-monorepo/assets/75506448/070ddd18-8b03-4d43-a8c0-9db94e285585

**Comment by kaynelynn** [comment]
<img width="1470" alt="image" src="https://github.com/ATXDAO/nouns-monorepo/assets/75506448/9ea175ef-d8a4-49c8-9761-ec7216be595f">

**Comment by willyogo** [comment]
thanks for reporting @kaynelynn and for the great video! i just tested with coinbase mobile wallet and it worked for me. would you mind trying again to see if this is resolved?

**Comment by JacobHomanics** [comment]
@kaynelynn Hey! Also tested this myself and could succesfully connect. Are you able to check yourself and see if you can connect?

**Comment by willyogo** [comment]
calling this fixed for now, can reopen if issue is reproducible
