### ISSUE TITLE
Create Dynamic Auction Algorithm

### ISSUE THREAD

**Issue by JacobHomanics** [ATXDAO/nouns-monorepo#33]
https://shapeshift.notion.site/ATX-Nouns-d9d25cae2e2b4e669e73edfb9af3ca20

**Comment by willyogo** [comment]
v0.1 of the dynamic auction algo was merged last night 🎉 
https://github.com/ATXDAO/nouns-monorepo/pull/41

last step is to add the moving average function, will make an issue for that now
