### ISSUE TITLE
404 error when attempting to view previously minted nouns from the Auction page

### ISSUE THREAD

**Issue by willyogo** [ATXDAO/nouns-monorepo#40]
Currently the staging app will break if a user attempts to view previously minted Nouns. Users should be able to view previously minted nouns either by clicking the arrows on the auction page or by visiting the correct URL.

Steps to reproduce:
1. visit https://member-portal-git-drquinn-nounsongo-members-atxdao.vercel.app/auction 
2. click the <- arrow on the auction to view the last noun minted
3. URL updates https://member-portal-git-drquinn-nounsongo-members-atxdao.vercel.app/noun/X and auction page displays a 404 error

AC:
1. Users can click the arrows to go back and forward between past and current Nouns auctions
2. if a user visits a URL for a specific auction, the corresponding auction details are displayed

**Comment by JacobHomanics** [comment]
fixed!
