### ISSUE TITLE
On mainnet deploy: Send mint proceeds to ATX DAO Treasury instead of ATX Nouns treasury

### ISSUE THREAD

**Issue by willyogo** [ATXDAO/nouns-monorepo#48]
when an atx noun is minted, proceeds are sent to the ATX DAO Treasury: [0x407Cf0e5Dd3C2c4bCE5a32B92109c2c6f7f1ce23](https://etherscan.io/address/0x407Cf0e5Dd3C2c4bCE5a32B92109c2c6f7f1ce23)

**Comment by JacobHomanics** [comment]
This seems to already be done. 

The multi-sig is set to be the "NounsDAOExecutor", meaning that it will receive funds from the auctions, is the owner of the Nouns Auction House, and is presumably able to have control over many other important aspects.

However, this was originally set to a, to be deployed, NounsDAOExecutor.sol smart contract. This smart contract seems to have an "admin (i.e. a multi-sig)", that can queue up, cancel, or execute transactions. It simply looks to be an extra safety mechanism with timelock features. Not sure if this will be needed or if simply leaving things as they are so that the multi-sig is the direct owner of everything.

Thoughts?

**Comment by willyogo** [comment]
@Hotmanics thanks for checkin, great news if this is already done! I just checked the staging environment for https://github.com/ATXDAO/nouns-monorepo/pull/56 though and it appears the proceeds are being sent to this address
https://goerli.etherscan.io/address/0xfe899a659eb87a8cdbe0d348cd2b8c7f48c66bd8

and on @spatializes' dynamic auction algorithm branch that we merged last night, the proceeds from the auction were sent to this address
https://goerli.etherscan.io/address/0xee0ec63f5a1f0bf161051bcdcb82cd9764131c0e#internaltx

Instead, the proceeds from auctions should be sent to the existing ATX DAO Treasury. However, because the ATX DAO treasury isn't deployed on goerli, it would be great to keep the owner of the contracts and recipient of proceeds as the deployer of the contracts in staging, and then in prod have owner + proceeds set to ATX DAO Treasury. https://goerli.etherscan.io/address/0x407Cf0e5Dd3C2c4bCE5a32B92109c2c6f7f1ce23
https://etherscan.io/address/0x407Cf0e5Dd3C2c4bCE5a32B92109c2c6f7f1ce23

That said, I do think it would make sense to go ahead and deploy the NounsDAOExecutor.sol smart contract when ATX Nouns launches because
1. we can avoid the work to remove it and risk of that breaking other things
2. if ATX DAO ever decides that it wants to migrate to a Nouns treasury and onchain governance, it will be easy to assign ownership to the already deployed contracts and transfer funds to the ATX Nouns treasury. That said, would be good to confirm that the owner of the nouns contracts (atx dao treasury) can update where the proceeds of the auction are sent to

lmk if i'm misunderstanding anything. like maybe we just need to set ATXDAO treasury to be the admin of NounsDAOExecutor.sol? idk, but would like atx dao treasury to receive the proceeds from the auction as well as every 10th atx noun (will make a separate issue for this; it's already set up to do this, but is sending to nounders.eth instead of atxdao.eth) and be able to update things like the parameters on the NounsAuctionHouse.sol, where proceeds of the auction are sent, and the owner/admin of the relevant contracts

**Comment by JacobHomanics** [comment]
@willyogo Forgive me, as I now have a much better understanding of how the code works.

Ok so we DO NOT need to make any PRs or code changes to make the issue's request possible. 

Thus, ignore all of the previous conversation and perceptions.

By default, when we run the deploy script, it will default the noundersDAO variable on the NounsToken instance to the deployer address. So the ones you are seeing for the testnets are probably some of @spatializes's deployer addresses. Brent, can you confirm? 

However, when we run the deploy script, it's already built in to optionally pass in a custom noundersDAO address.

I.E. Normally I would run something like:
`npx hardhat deploy --network goerli`

when we get to mainnet, or situations where we want the multi-sig to be set as noundersDAO, then we'll do something like:
`npx hardhat deploy --network mainnet --update-configs --noundersdao 0x407Cf0e5Dd3C2c4bCE5a32B92109c2c6f7f1ce23`

Thus, resulting in NounsToken to be configured like so: [NounsToken (Etherscan)](https://goerli.etherscan.io/address/0xf2384BEb38D00b319EA3E0D3D890425F3eC43329#readContract)!

Let me know if theres still some unanswered questions or if I'm still missing a point on this!

**Comment by willyogo** [comment]
perfect! thanks for taking the time to understand the code and figure this out 🙏 

this sounds like the plan!

> when we get to mainnet, or situations where we want the multi-sig to be set as noundersDAO, then we'll do something like:
> npx hardhat deploy --network mainnet --update-configs --noundersdao 0x407Cf0e5Dd3C2c4bCE5a32B92109c2c6f7f1ce23
