### ISSUE TITLE
Treasury etherscan link doesn't work on testnet.

### ISSUE THREAD

**Issue by JacobHomanics** [ATXDAO/nouns-monorepo#78]
When clicking on the dao treaury link in the top left, it takes you to a "not found" etherscan link.

**Comment by willyogo** [comment]
was able to repro this in prod.

Also noticed that the amount displayed is less than the amount displayed on etherscan. let's see if we can get 2 birds stoned at once and get the website to display the same amount as etherscan.
![image](https://github.com/ATXDAO/nouns-monorepo/assets/26232238/a36c793d-a6cb-4bf1-9789-809de42f8d0a)

![image](https://github.com/ATXDAO/nouns-monorepo/assets/26232238/8b84780b-f44d-4cc3-80a9-cc35e63f5c5e)

https://etherscan.io/address/0x407Cf0e5Dd3C2c4bCE5a32B92109c2c6f7f1ce23#multichain-portfolio
